tag 101 :
  x : 0
  y : 0
  z : 0
tag 102 :
  x : 0
  y : 0
  z : 0
tag 103 :
  x : 0
  y : 0
  z : 0
tag 104 :
  x : 0
  y : 0
  z : 0
tag 105 :
  x : 0
  y : 0
  z : 0
tag 106 :
  x : 0
  y : 0
  z : 0
tag 107 :
  x : 0
  y : 0
  z : 0
tag 108 :
  x : 0
  y : 0
  z : 0
tag 109 :
  x : 0
  y : 0
  z : 0
tag 110 :
  x : 0
  y : 0
  z : 0
tag 111 :
  x : 0
  y : 0
  z : 0
tag 112 :
  x : 0
  y : 0
  z : 0
tag 113 :
  x : 0
  y : 0
  z : 0
tag 114 :
  x : 0
  y : 0
  z : 0
tag 115 :
  x : 0
  y : 0
  z : 0
tag 116 :
  x : 0
  y : 0
  z : 0
tag 117 :
  x : 0
  y : 0
  z : 0
tag 118 :
  x : 0
  y : 0
  z : 0
tag 119 :
  x : 0
  y : 0
  z : 0
tag 120 :
  x : 0
  y : 0
  z : 0
tag 121 :
  x : 0
  y : 0
  z : 0
tag 122 :
  x : 0
  y : 0
  z : 0
tag 123 :
  x : 0
  y : 0
  z : 0
tag 124 :
  x : 0
  y : 0
  z : 0
tag 125 :
  x : 0
  y : 0
  z : 0
tag 126 :
  x : 0
  y : 0
  z : 0
tag 127 :
  x : 0
  y : 0
  z : 0
tag 128 :
  x : 0
  y : 0
  z : 0
tag 129 :
  x : 0
  y : 0
  z : 0
tag 130 :
  x : 0
  y : 0
  z : 0
tag 131 :
  x : 0
  y : 0
  z : 0
tag 132 :
  x : 0
  y : 0
  z : 0
tag 133 :
  x : 0
  y : 0
  z : 0
tag 134 :
  x : 0
  y : 0
  z : 0
tag 135 :
  x : 0
  y : 0
  z : 0
tag 136 :
  x : 0
  y : 0
  z : 0
tag 137 :
  x : 0
  y : 0
  z : 0
tag 138 :
  x : 0
  y : 0
  z : 0
tag 139 :
  x : 0
  y : 0
  z : 0
tag 140 :
  x : 0
  y : 0
  z : 0
tag 141 :
  x : 0
  y : 0
  z : 0
tag 142 :
  x : 0
  y : 0
  z : 0
tag 143 :
  x : 0
  y : 0
  z : 0
tag 144 :
  x : 0
  y : 0
  z : 0
tag 145 :
  x : 0
  y : 0
  z : 0
tag 146 :
  x : 0
  y : 0
  z : 0
tag 147 :
  x : 0
  y : 0
  z : 0
tag 148 :
  x : 0
  y : 0
  z : 0
tag 149 :
  x : 0
  y : 0
  z : 0
tag 150 :
  x : 0
  y : 0
  z : 0