tag 0 :
  x : 0
  y : 0
  z : 0
tag 1 :
  x : 0
  y : 0
  z : 0
tag 2 :
  x : 0
  y : 0
  z : 0
tag 3 :
  x : 0
  y : 0
  z : 0
tag 4 :
  x : 0
  y : 0
  z : 0
tag 5 :
  x : 0
  y : 0
  z : 0
tag 6 :
  x : 0
  y : 0
  z : 0
tag 7 :
  x : 0
  y : 0
  z : 0
tag 8 :
  x : 0
  y : 0
  z : 0
tag 9 :
  x : 0
  y : 0
  z : 0